Update pipeline.yml

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -444,7 +444,23 @@ stages:
       else 
           echo -e "${red}Kubernetes deployment file '${DEPLOYMENT_FILE}' not found${no_color}"
           exit 1
-      fi    
+      fi 
+      
+      
+      
+      INGRESS_DOMAIN=hello
+      INGRESS_SUBDOMAIN=$(ibmcloud ks cluster-get --cluster ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep "Ingress Subdomain" | cut -d':' -f 2 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
+      echo -e "Updating ${DEPLOYMENT_FILE} with ingress host: ${INGRESS_DOMAIN}.${INGRESS_SUBDOMAIN}"
+      if [ -f ${DEPLOYMENT_FILE} ]; then
+          #sed -i "s~^\([[:blank:]]*\)host:.*$~\host: ${INGRESS_DOMAIN}.${INGRESS_SUBDOMAIN}~" ${DEPLOYMENT_FILE}
+          sed -i "s~\host:.*$~\host: ${INGRESS_DOMAIN}.${INGRESS_SUBDOMAIN}~" ${DEPLOYMENT_FILE}
+          cat ${DEPLOYMENT_FILE}
+      else 
+          echo -e "${red}Kubernetes deployment file '${DEPLOYMENT_FILE}' not found${no_color}"
+          exit 1
+      fi
+      
+      
       set -x
       kubectl apply --namespace ${CLUSTER_NAMESPACE} -f ${DEPLOYMENT_FILE} 
       set +x
